#!/bin/sh

. "$HOME"/.config/hypr/sakoora.hyprlock/colors-hyprlock.sh
percentage() {
	total_max=0
	total_current=0
	total_percent=0
	percent_count=0
	for battery in /sys/class/power_supply/BAT*; do
		[ -d "$battery" ] || continue
		if [ -r "$battery/energy_now" ] && [ -r "$battery/energy_full" ]; then
			current=$(cat "$battery/energy_now")
			max=$(cat "$battery/energy_full")
			total_max=$((total_max+max))
			total_current=$((total_current+current))
		elif [ -r "$battery/charge_now" ] && [ -r "$battery/charge_full" ]; then
			current=$(cat "$battery/charge_now")
			max=$(cat "$battery/charge_full")
			total_max=$((total_max+max))
			total_current=$((total_current+current))
		elif [ -r "$battery/capacity" ]; then
			total_percent=$((total_percent+$(cat "$battery/capacity")))
			percent_count=$((percent_count+1))
		fi
	done
	if [ "$total_max" -gt 0 ]; then
		echo $((total_current*100/total_max))
	elif [ "$percent_count" -gt 0 ]; then
		echo $((total_percent/percent_count))
	else
		echo 0
	fi
}

status() {
	if [ "$desktop" -eq "1" ]; then
		echo " "
		exit
	fi
	bat_count=0
	a_count=0
	b_count=0
	for battery in /sys/class/power_supply/BAT*; do
		[ -d "$battery" ] || continue
		status=$(cat "$battery"/status)
		case "$status" in
			"Charging" )
				return 1;;
			"Discharging" )
				return 2;;
			"Not charging" )
				a_count=$((a_count+1));;
			"Full" )
				b_count=$((b_count+1));;
		esac
		bat_count=$((bat_count+1))
	done
	if [ "$a_count" -eq "$bat_count" ]; then
		status="Not charging"
		return 3
	elif [ "$b_count" -eq "$bat_count" ]; then
		status="Full"
		return 4
	else
		status="Unknown"
		return 5
	fi
}

indicator() {
	if [ "$desktop" -eq "1" ]; then
		echo "<span background='$background' foreground='$color2'> On desktop </span>"
		exit
	fi
	percent=$(percentage)
	status
	case $? in
		1 )
			symbol="<span>  </span>";;
		2 )
			symbol="<span weight='bold'> ! </span>";;
		3 )
			symbol="<span>  </span>";;
		4 )
			symbol="<span>  </span>";;
		5 )
			symbol="<span weight='bold'> ? </span>";;
	esac
	if [ $percent -gt 90 ]; then
		echo "<span background='$background' foreground='$color2'>    $symbol    </span>"
	elif [ $percent -gt 80 ]; then
		echo "<span background='$background' foreground='$color2'>    $symbol   </span> <span foreground='$color2'></span>"
	elif [ $percent -gt 70 ]; then
		echo "<span background='$background' foreground='$color2'>    $symbol  </span>  <span foreground='$color2'></span>"
	elif [ $percent -gt 60 ]; then
		echo "<span background='$background' foreground='$color2'>    $symbol </span>   <span foreground='$color2'></span>"
	elif [ $percent -gt 50 ]; then
		echo "<span background='$background' foreground='$color2'>    $symbol</span>    <span foreground='$color2'></span>"
	elif [ $percent -gt 40 ]; then
		echo "<span background='$background' foreground='$color2'>    </span>$symbol    <span foreground='$color2'></span>"
	elif [ $percent -gt 30 ]; then
		echo "<span background='$background' foreground='$color2'>   </span> $symbol    <span foreground='$color2'></span>"
	elif [ $percent -gt 20 ]; then
		echo "<span background='$background' foreground='$color2'>  </span>  $symbol    <span foreground='$color2'></span>"
	elif [ $percent -gt 10 ]; then
		echo "<span background='$background' foreground='$color2'> </span>   $symbol    <span foreground='$color2'></span>"
	else
		echo "<span background='$background' foreground='$color2'></span>    $symbol    <span foreground='$color2'></span>"
	fi
}

if [ -d /sys/class/power_supply/BAT0 ] || [ -d /sys/class/power_supply/BAT1 ]; then
	desktop=0
else
	desktop=1
fi
case "$1" in
	"-i" )
		indicator;;
	"-p" )
		if [ "$desktop" -eq "1" ]; then
			echo "<span>  </span>"
		else
			echo "$(percentage)%"
		fi;;
	"-s" )
		status
		echo "<span style='italic' weight='light'> $status </span>";;
esac
